### PR TITLE
Boilerplate: Update to 25bf1477435cc1d54ed1a0dff1c1f16405144db3

### PR DESCRIPTION
**Pull request by 2uasimojo**
Conventions:
- openshift/golang-osd-operator: Update
---
https://github.com/openshift/boilerplate/compare/4486e69a0b1af4b3644a90a87fea0908e336a04a...25bf1477435cc1d54ed1a0dff1c1f16405144db3

commit: 567b9545e8fbdc825306c7d8a4ec1bfe2c893236
author: Eric Fried
openshift/golang-osd-operator: openapi-gen

Make consumers produce openapi by adding a target called
`openapi-generate` which runs `openapi-gen` if necessary. Put it in the
chain for `generate`.

commit: a0f4fba9914a5d95a5605f59e5fb87759917f3c8
author: Eric Fried
Image: Fix tests for image-v0.4.0

commit: 7bcdbc25c7614d5053a5bcef337bd4fbcb9f23a7
author: Eric Fried
Image: Install mockgen and openapi-gen

These will be used by `go-generate` and `op-generate`, respectively.

commit: c1b444f2f0fafc06afdee1f87629096e7185d11a
author: Eric Fried
Image: Don't use gvm

It turns out we don't need go1.14, so we don't need gvm. If we need to
upgrade the version of go used by consumers, we'll instead update the
backing image.

This (mostly) reverts commit 5efde524a0104b8b076f721144469934ac033391.

commit: e654a8ad5d75e0da63888b5be944ad605de2b226
author: Eric Fried
Update subscribers

...and fix a buglet introduced by 4feb777c that breaks on downlevel or
not-yet-onboarded consumers.

commit: 8159de6a4550f652c1033097f5b89a819cc11dd6
author: Eric Fried
pr-check: Color test output

...so it can be visually distinguished from the output of the commands
run by the tests. This will make debugging easier.

### CODE REVIEW

**Review by 2uasimojo — COMMENTED** [review]
/hold

Needs a fixup commit.

**Review by 2uasimojo — COMMENTED** [review]
/retest

Get real results now that the boilerplate backing image is [properly mirrored](https://github.com/openshift/release/pull/14879)

**Comment by rporres** [comment]
What's missing here, @2uasimojo ? 

```
  * could not resolve inputs: could not determine inputs for step [input:root]: could not resolve base image: imagestreamtags.image.openshift.io "boilerplate:image-v0.4.0" not found
time="2021-01-15T00:15:32Z" level=info msg="Reporting job state 'failed' with reason 'resolving_inputs'"

**Comment by 2uasimojo** [comment]
> What's missing here, @2uasimojo ?
> 
> ```
>   * could not resolve inputs: could not determine inputs for step [input:root]: could not resolve base image: imagestreamtags.image.openshift.io "boilerplate:image-v0.4.0" not found
> time="2021-01-15T00:15:32Z" level=info msg="Reporting job state 'failed' with reason 'resolving_inputs'"
> ```

The CI environment needs to map the image (which is new, as of yesterday). It’s working for all the projects in the openshift/ org. Not sure what the issue is here. We’ll have to ask dptp. But I’m out today and on call next week so it might be a while. Nothing really urgent about this.

**Comment by 2uasimojo** [comment]
> Needs a fixup commit.

No it doesn't.

/hold cancel

**Pull request merged**
