### PR TITLE
Boilerplate: Update to 0ba6566d544d0df9993a92b2286c131eb61f3e88

### PR DESCRIPTION
**Pull request by 2uasimojo**
Conventions:
- openshift/golang-osd-operator: Update
---
https://github.com/openshift/boilerplate/compare/935fc6adc17ca29a1fe70dbd6f1d8c8b07c9580f...0ba6566d544d0df9993a92b2286c131eb61f3e88

commit: 7679eeabd8af9bcd1deb2ef998d862e275fdb3f2
author: Eric Fried
Split out stderr for `skopeo inspect`

This started happening suddenly:

```
10:08:43 parse error: Invalid literal at line 1, column 6
10:08:43 Unexpected error: skopeo inspect succeeded, but output contained no .Digest
10:08:43 Here's the output:
10:08:43 time="2021-05-10T15:08:41Z" level=error msg="HEADER map[Content-Length:[185] Content-Type:[text/html] Date:[Mon, 10 May 2021 15:08:41 GMT] Server:[nginx/1.12.1]]"
10:08:43 {
10:08:43     "Name": "quay.io/app-sre/aws-account-operator",
10:08:43     "Digest": "sha256:02baefe6abe17a60f9751441fdd7223b3d79af5580639d4ea90285bbab28a0c7",
```

For some reason, `skopeo inspect` is now producing that header
information on stderr, whereas it wasn't before.

Nevertheless, that's no excuse for glomming together stdout and stderr
when we expect to be able to parse the former. So with this commit, we
split stderr out and redirect it to a temporary file instead.

commit: 9f62838f2f7eba3573d83400d2b227655f71b399
author: Eric Fried
Support building multiple images

Previously the app-sre pipeline scripts were designed to build/push (if
not already extant) exactly two things: the operator image and the OLM
catalog.

With this commit we allow the consumer to build arbitrary images in
addition to the operator image by setting a multiline `make` variable as
follows:

```make
define ADDITIONAL_IMAGE_SPECS
./path/to/a/Dockerfile $(IMAGE_REGISTRY)/$(IMAGE_REPOSITORY)/a-image:v1.2.3
./path/to/b/Dockerfile $(IMAGE_REGISTRY)/$(IMAGE_REPOSITORY)/b-image:v4.5.6
endef
```

NOTE: As an ancillary side effect (benefit) of this commit, we stop
tagging `latest` operator images. They were unused at best, misused at
worst.

commit: cc2ba9070df73175397f4d36ffeaadae073d240f
author: Eric Fried
Add splunk-forwarder-operator as a subscriber

commit: f03b007a8a2bb12183b611ed231cef5a82ef8f7d
author: Christoph Blecker
Use /usr/bin/env bash everywhere

commit: bf324c0b4fbf95930caf2613f60f362bc32e8469
author: Dominic Finn
help to makefile

commit: 06e3d461cbccc2f73bd2b67a8e6173def1ccb2eb
author: Christoph Blecker
Make sed prompt to use compatible sed

commit: 29ea0a0182e40bed2d90c162b084e96d6643c75a
author: Eric Fried
Subscriber updates

All registered operators are onboarded at this point.

commit: 01138a140ecac9b3c761408c5f75d667e9a0ff52
author: Dominic Finn
Update boilerplate/_lib/container-make

Co-authored-by: Eric Fried <2uasimojo@users.noreply.github.com>

commit: 1d066c78317c923381571167f98e53f44478f01c
author: Dominic Finn
podman build logic

commit: 4a28e9b440b478795346b68bc2c8a0d6f29deee2
author: Christoph Blecker
Fix codecov job errors

commit: 5522c6bdcda11035e975bcf7898e1709950f2792
author: Christoph Blecker
Persist codecov script used as a test artifact

commit: 12e79262e14bd97051e12c34ef4a11ecfd958764
author: Kirk Bater
removes debug flag from container-make

commit: 994bbe4f92687be3a386fe26ee28331c8f1c07cb
author: Arjun Naik
Error when unsupported resources present

Signed-off-by: Arjun Naik <anaik@redhat.com>

commit: 63afc0b627ce08a08abe95b9e5b62440ff1d3dba
author: Eric Fried
app-sre.md: Remove references to REGISTRY_USER/_TOKEN

These are no longer necessary since 272a910

commit: 9d00c82de0a3c05d3d3d0864d9196640df11472f
author: Benjamin Dematteo
enabling back codecov as we are clear from the incident

commit: 272a910b67ee97c8085b1a9d8dd741f14d25f433
author: Benjamin Dematteo
Replacing REGISTRY_USER and REGISTRY_TOKEN bu QUAY_USER/QUAY_TOKEN for make docker-login

commit: f49517a7e1623c641772ebde965bd60e5091ad2e
author: Eric Fried
Disable codecov

...while we investigate a [codecov.io security
breach](https://about.codecov.io/security-update/)

commit: d3c263cee468dc862b9bb108cd6e6c86297f3585
author: Benjamin Dematteo
Adding missing varaible for git token auhtent

commit: 40db4e9aac5cae0b1fa5f71ca7170b762ef8ec5c
author: Arjun Naik
Remove flags for interactive docker run for the CSV generation

Signed-off-by: Arjun Naik <anaik@redhat.com>

commit: 38876608dfa38d552f368837b1e8faa5955aa215
author: Eric Fried
Fix CI: Support disabling SaaS file checks

The 06-csv-generate test invokes (make targets that invoke)
csv-generate.sh, which now queries the operator's SaaS file in
app-interface to determine whether it's a hive or cluster operator.
Since the test uses a dummy project, it has no such SaaS file in
app-interface. Even if it did, the CI image doesn't have the right certs
to query it over https.

This commit enables an environment variable to bypass that whole section
of csv-generate.sh, and enables it in the test case.

commit: 380d825ff9e137cd6fccff62f2035872a6be3daf
author: James Harrington
Containerize yq

commit: 0378b16b89cba33fecea0447f306eadd3b979d82
author: James Harrington
Ensure we fetch a valid deployed production hash

commit: 5f1d9a464728641d0c5ea1828fed7b5b2361c99f
author: Arjun Naik
Small improvements to make it easier to run csv-generate test locally

Signed-off-by: Arjun Naik <anaik@redhat.com>

commit: b926c8703e255748b632d0dabdb061f439b581d4
author: Arjun Naik
Updated the hack generation script

Signed-off-by: Arjun Naik <anaik@redhat.com>

commit: 7973db3122b3f0bbade38cf95bc3ab1aa1b84e25
author: Eric Fried
Run CSV generator in a container

...unless we're already in a container.

...because we can't rely on py3 being present on jenkins nodes, and py2
is dead.

[OSD-6993](https://issues.redhat.com/browse/OSD-6993)

commit: 639160e9a92475f0a446c44aff3ad202d935e83e
author: Arjun Naik
Updated test case for CSV generation

Signed-off-by: Arjun Naik <anaik@redhat.com>

commit: 1dc94f0588ad8177e8804a8adf3bed94333453ec
author: Arjun Naik
Use trim_index and add default namespace for rolebinding subject SA

Signed-off-by: Arjun Naik <anaik@redhat.com>

commit: 2c6032115302c4449b8843b076a59d0cf2d25fa9
author: Arjun Naik
Add roles into CSV permissions

Signed-off-by: Arjun Naik <anaik@redhat.com>

commit: a9321bb73ef42b9e30d3ec7673ddc1b7f3c99876
author: Eric Fried
csv-generate: Use the project's major.minor

Finishes resolving a
[TODO](https://github.com/openshift/boilerplate/commit/8e99ebe14d1c7c547c9de3fa5d94e876fd674f8d#diff-424ddf34b68cef0633f4520f756a919d70a24880b5ab931d3cd85d17f8659b5fL93-R110)
whereby the csv generator scripts were hardcoding the operator's
major.minor version to 0.1.

With this commit, common-generate-operator-bundle.py no longer accepts
separate arguments for commit number or hash to construct the
`{major}.{minor}.{commit-count}-{commit-hash}`. It now accepts `-V
operator-version` where `operator-version` is already in that form.

commit: b707cd183bce5fbe1281109cdbf211c607d054f8
author: Eric Fried
Generate operator bundle generically and inclusively

This is an almost-total rewrite of the common operator bundle generator
script to accommodate variations in boilerplate consumers.

Before: The script looked for specific files by name. This wasn't a big
deal as long as consumers had the right corresponding file they could
simply rename. However, it would blow up if those files weren't present
or didn't contain exactly what was expected; or (importantly) if more
than one file of that kind was needed.

After: The script processes all yaml documents under the deploy/
subdirectory, regardless of filename, including cases where multiple
yaml documents exist in a single file, and processes them based on their
Kind. The following are treated specially:

- CustomResourceDefinitions: These are registered as "owned" in the CSV.
Otherwise they are copied into the bundle directory as usual.
- ClusterRoles: These are folded into the CSV's `clusterPermissions` and
*not* copied into the bundle directory.
- ClusterRoleBindings: These are only used to discover the appropriate
`serviceAccountName` for their corresponding ClusterRoles. They are not
copied into the bundle directory. If any ClusterRoleBindings are "left
over" at the end (not used to find a ServiceAccount), an error is
raised.
- Deployment: We explicitly validate that there is exactly one of these.
We fold the contents into the CSV's `deployments`. The Deployment is
*not* copied to the bundle directory.
- ServiceAccounts: These are *ignored*, as we assume they correspond
exactly to those listed in ClusterRoleBindings or the Deployment's Pod
spec.

TODO:s
- The CSV
[schema](https://docs.openshift.com/container-platform/4.5/rest_api/operatorhub_apis/clusterserviceversion-operators-coreos-com-v1alpha1.html)
appears to support Role[Binding]s in a manner similar to
ClusterRole[Binding]s. Assuming OLM supports that, we should use it. For
now, this commit treats Role[Binding]s as generic resources and simply
copies them into the bundle, as consumers appeared to be doing.
- We should validate ServiceAccounts to make sure they correspond to
[Cluster]RoleBindings or Pod specs in the Deployment, and error if any
are "left over".

commit: bfcccf9262c7f9cd1fa7b9c0676a03fe476a579c
author: James Harrington
Removed to pass tests

commit: fa055ee00a16f0f25aba8542b4c441be161ce8cb
author: James Harrington
Include package.yaml in OLM bundle

commit: 32fa7dc294da442d1333551c5554652095c3306c
author: Eric Fried
golang-osd-operator: Pull operator image by digest

This commit tweaks the common CSV generator logic such that the operator
image is referenced by digest
(`{registry}/{repo}/{operator}@sha256:{digest}`) rather than by tag
(`{registry}/{repo}/{operator}:v{major}.{minor}.{count}-{commit-sha}`).

**NOTE:** This does not affect how the catalog image is pulled. That
requires changes in the app-interface saas file and the consuming
repository's OLM template.

commit: 4bba942de7a8d389a46f606c798a512c0f903d9b
author: Eric Fried
golang-osd-operator: Enable app-sre build and deploy

This commit adds the top-level script to perform the end-to-end app-sre
build and deploy sequence, and enables it by default for consumers via
the `build-push` make target.

It also enables (and documents) local testing of this sequence without
changing code.

commit: dec995b5d0a456d48898807f617580ec3c54d079
author: Eric Fried
Enable selecting test cases

With this commit, you can use a `CASE_GLOB` variable to restrict which
tests are run by `make test` (aka `make pr-check`). The value of
`CASE_GLOB` is passed to `find ... -name`, so may be anything that will
accept. For example, to run just the test case named `06-csv-generate`,
you can run:

```
make CASE_GLOB=06-csv-generate test
```

This also works via `container-make`, which can be convenient for
debugging CI failures:

```
./boilerplate/_lib/container-make CASE_GLOB=06-csv-generate pr-check
```

commit: 8e99ebe14d1c7c547c9de3fa5d94e876fd674f8d
author: Eric Fried
golang-osd-operator: Pull operator image by digest

This commit tweaks the common CSV generator logic such that the operator
image is referenced by digest
(`{registry}/{repo}/{operator}@sha256:{digest}`) rather than by tag
(`{registry}/{repo}/{operator}:v{major}.{minor}.{count}-{commit-sha}`).

**NOTE:** This does not affect how the catalog image is pulled. That
requires changes in the app-interface saas file and the consuming
repository's OLM template.

commit: aeca64eaa1fee9b69d0797e7d8bf06f792a907b8
author: Eric Fried
golang-osd-operator: Enable app-sre build and deploy

This commit adds the top-level script to perform the end-to-end app-sre
build and deploy sequence, and enables it by default for consumers via
the `build-push` make target.

It also enables (and documents) local testing of this sequence without
changing code.

commit: c937d6ab7756ea4f287ae828cd21dbd0e5415f20
author: Eric Fried
Enable container-make in boilerplate itself

Previously in order for `container-make` to function in the boilerplate
repository itself, you had to set the `LATEST_IMAGE_TAG` environment
variable manually. With this commit, if it's unset and we're in
boilerplate, we discover it from git.

commit: 05f546cc7e24911477b504df585f63dbd53445ba
author: Eric Fried
Document subscribers

Add documentation for the `subscribers.yaml` file and the `subscriber`
utility.

commit: 10166fa7731ab847c291a85e78b4f0318f52a0b2
author: Benjamin Dematteo
Fixing the bad variable used for calling the generate scripts

commit: 0813021e913229a7f0c62a4f86c3a0814b627bc7
author: James Harrington
Erroneous additional parameter specified

commit: d7c8056d99bade30bed6fdc4d376ce979bfa8558
author: Eric Fried
Pin yq to 3.4.1 in csv-generate.sh

See openshift/osd-metrics-exporter#43 for details.

commit: cf31f7abe2964e70b6fdef249ac984822bce0cef
author: Eric Fried
image-v0.5.1: registry.svc.ci.openshift.org is dead

We need to build our image `FROM registry.ci.openshift.org` now, since
`registry.svc.ci.openshift.org` has been decommissioned.

image-v0.5.0 will never build and is therefore unusable.

commit: 96415a636afa0e304dbdab60318fd4f9e2bbc825
author: Manuel Dewald
add operator-sdk v1.2.0

commit: 19951d141e1c7a2b371a5ec34784e7005c073345
author: Eric Fried
image-v0.5.0: more go helpers

Add the following to the backing image:
- controller-gen
- kustomize
- go-bindata

### CODE REVIEW

**Comment by 2uasimojo** [comment]
/test coverage

token has been updated

**Comment by 2uasimojo** [comment]
/test coverage

This was still using the old token. Deleted the CI build in case it was because of cache.

**Comment by 2uasimojo** [comment]
/test coverage

Updated secret in vault, *maybe*?

**Review by rrati — APPROVED** [review]

**Pull request merged**
