### PR TITLE
Allow custom linter config

### PR DESCRIPTION
**Pull request by rporres**
Signed-off-by: Rafa Porres Molina <rporresm@redhat.com>

### CODE REVIEW

**Comment by 2uasimojo** [comment]
Ah, so bp isn't going to let you do this :)

Since you last looked, we added a check to prevent consumers from editing bp-controlled files.

**Comment by rporres** [comment]
`make build` and `make docker-build` work for me locally 😅

**Comment by 2uasimojo** [comment]
Part of the package will be standardizing prow configs, one of which will be to run `make validate`, which runs `freeze-check`, which will fail for the reason cited above.

This would be an eminently sane thing to propose to boilerplate itself... if we were willing to allow customizations like this. Perhaps you can do that and we can have the discussion there?

**Comment by rporres** [comment]
Done in https://github.com/openshift/boilerplate/pull/74

**Comment by 2uasimojo** [comment]
Responded in https://github.com/openshift/boilerplate/pull/74.

I'm curious why you want to do this, since you're already lint-free using the (stricter) config in the convention. YAGNI.

**Comment by rporres** [comment]
We won't follow this path. See https://github.com/openshift/boilerplate/pull/74 to get more details

**Pull request closed without merging**
