### PR TITLE
Do not wrap main in or condition

### PR DESCRIPTION
**Pull request by rporres**
Signed-off-by: Rafa Porres Molina <rporresm@redhat.com>

### CODE REVIEW

**Comment by rporres** [comment]
It is needed because `set -e` does not affect conditions. I found a great way to deactivate it completely 😂  As an example, if I execute this code 
```
set -e

function fail() {
    ls /noo
}

fail || echo "adios"
echo "hola"
```
I get
```
ls: cannot access '/noo': No such file or directory
adios
hola
```

**Comment by 2uasimojo** [comment]
That's because `echo "adios"` succeeds. Change that to `exit 1` and `hola` is never printed.

**Comment by 2uasimojo** [comment]
Though interestingly, whereas `ls /bar || ls /baz` triggers immediate failure after running both sides, `ls /bar && ls /baz` does not trigger immediate failure, which I find weird.

Anyway, it's a fine change -- I assume you intend to propose it to boilerplate.

**Comment by rporres** [comment]
> That's because echo "adios" succeeds. Change that to exit 1 and hola is never printed.

My point is that I've managed to deactivate the `set -e`. I guess I didn't explain well what I have in mind. Take a look to this script:

```
set -e

function fail() {
    ls /noo
    echo "good"
}

fail || { echo "I've failed"; exit 1; }
echo "I'm still alive"
```
which executes as
```
ls: cannot access '/noo': No such file or directory
good
I'm still alive
```
whereas if i don't check immediately with an or
```
set -e

function fail() {
    ls /noo
    echo "good"
}

fail
echo "I'm still alive"
```
it fails immediately
```
ls: cannot access '/noo': No such file or directory
```

**Comment by rporres** [comment]
> Anyway, it's a fine change -- I assume you intend to propose it to boilerplate.

Yes, I want it to go through a real pipeline before adding it to boilerplate

**Pull request merged**
