### PR TITLE
Run additional golangci checks

### PR DESCRIPTION
**Pull request by rporres**
These will be run on top of what boilerplate offers. See https://github.com/openshift/boilerplate/pull/92

Signed-off-by: Rafa Porres Molina <rporresm@redhat.com>

### CODE REVIEW

**Comment by rporres** [comment]
cc @2uasimojo @rrati

**Review by 2uasimojo — COMMENTED** [review]
Yeah, this looks legit to me.

Why are you removing all those other checks?

**Comment by rporres** [comment]
> Why are you removing all those other checks?

Because they are already covered by the standard boilerplate config

**Review by rrati — APPROVED** [review]
lgtm

**Comment by 2uasimojo** [comment]
> > Why are you removing all those other checks?
> 
> Because they are already covered by the standard boilerplate config

Ah, okay, I guess that makes sense... unless we decide to remove them from bp. Which I doubt we'll do, so cool.

**Pull request merged**
