### PR TITLE
Adding architecture documentation to DVO project

### PR DESCRIPTION
**Pull request by npecka**
Submitting architecture diagrams to DVO project to assist in understanding the overall picture for DVO

### CODE REVIEW

**Comment by bkez322** [comment]
I haven't yet found the opportunity to really dive into this with great detail what I'd suggest to be added to or amended with this, but I do thank you again for getting this started! It's not easy to go from near-nothing to something with documentation for any project.

The goal of this PR, in my opinion, should be to produce documentation that someone with minimal understanding of this project can look at, and come out with an excellent understanding of how the project works, and that person should be able to confidently explain the project to other people. I don't think this PR is accomplishing this at the moment. I feel this PR is significantly lacking in descriptive context on what the significant parts of DVO are actually doing and how they work.

I intend to offer further, more specific and constructive suggestions to this in the near-future, but I think a good next step would be to accompany these 2 diagram you made with written descriptions of what each piece in the diagrams is doing, and what the arrows connecting them actually mean.

**Comment by bkez322** [comment]
I think the first DVO_Arch.drawio.png diagram is busy and confusing in its current state.

It looks like its trying to combine all the following in a single diagram:
* DVO-human-developer workflow (what things does a DVO developer interact with? why?)
* DVO-human-consumer workflow (what things does a person that wants to install DVO to a openshift cluster interact with? why?)
* structure of a complete operator-managed DVO deployment (what k8s resources does deploying [this](https://github.com/app-sre/deployment-validation-operator/blob/master/deploy/openshift/deployment-validation-operator-olm-with-polling.yaml) create? What do each of these k8s resources do? How they talk to each other?)
* structure of a complete DVO "observability" deployment (what k8s resources does [this](https://github.com/app-sre/deployment-validation-operator/blob/master/deploy/observability/template.yaml) create? What do each of these k8s resources do? How they talk to each other?)
* the structure of DVO's internal codebase ( what are the major dependencies within DVO's codebase? The 2 big ones are kube-linter and the promtheus library. What are these libraries doing currently?)

I would love to see the 2 diagrams we have today split cleanly into 5 separate diagrams as described here. 😀

**Review by bkez322 — CHANGES_REQUESTED** [review]
(see friendly suggestions above)

**Comment by npecka** [comment]
> (see friendly suggestions above)

I have pushed a change that introduces 5 new diagrams. They are still in rough draft form and will need to be revised to look more aesthetically pleasing. Looking for feedback on the information that goes along with them and what needs to be added / how you're looking for things to be worded. @bkez322 Please take a look and let me know your feedback once you have the chance. Thanks!

**Comment by hlipsig** [comment]
@npecka  you've got an incorrect link: /images/DVO_Observability.drawio.png on line 32 of Architecture.md the filename has as space not an underscore "DVO Observability.drawio.png" so you'll either want change line 32 or remove it. It's referenced correctly later in the doc, so maybe you were looking to reference a different drawing here?

**Review by hlipsig — APPROVED** [review]
We can iterate over this with time, but it's better to have something.

**Review by hlipsig — APPROVED** [review]

**Review by bkez322 — COMMENTED** [review]
Sorry I'm late to comment, but LGTM!

**Pull request merged**
